import type { Program } from './types';

/** A small illustrative B.Sc. in Computer Science to show the layout. */
export const sampleProgram: Program = {
  name: 'Computer Science',
  degree: 'B.Sc.',
  institution: 'My University',
  years: 3,
  requiredCredits: 120,
  showSummer: false,
  courses: [
    {
      id: 'c-calc1',
      code: 'MATH101',
      name: 'Calculus 1',
      credits: 5,
      type: 'mandatory',
      category: 'Mathematics',
      year: 1,
      semester: 'A',
      prerequisites: [],
    },
    {
      id: 'c-linalg',
      code: 'MATH102',
      name: 'Linear Algebra',
      credits: 5,
      type: 'mandatory',
      category: 'Mathematics',
      year: 1,
      semester: 'A',
      prerequisites: [],
    },
    {
      id: 'c-intro',
      code: 'CS101',
      name: 'Introduction to Computer Science',
      credits: 6,
      type: 'mandatory',
      category: 'Core CS',
      year: 1,
      semester: 'A',
      prerequisites: [],
    },
    {
      id: 'c-calc2',
      code: 'MATH103',
      name: 'Calculus 2',
      credits: 5,
      type: 'mandatory',
      category: 'Mathematics',
      year: 1,
      semester: 'B',
      prerequisites: ['c-calc1'],
    },
    {
      id: 'c-ds',
      code: 'CS102',
      name: 'Data Structures',
      credits: 6,
      type: 'mandatory',
      category: 'Core CS',
      year: 1,
      semester: 'B',
      prerequisites: ['c-intro'],
    },
    {
      id: 'c-algo',
      code: 'CS201',
      name: 'Algorithms',
      credits: 6,
      type: 'mandatory',
      category: 'Core CS',
      year: 2,
      semester: 'A',
      prerequisites: ['c-ds'],
    },
    {
      id: 'c-os',
      code: 'CS202',
      name: 'Operating Systems',
      credits: 5,
      type: 'mandatory',
      category: 'Systems',
      year: 2,
      semester: 'B',
      prerequisites: ['c-ds'],
    },
    {
      id: 'c-seminar',
      code: 'CS390',
      name: 'Research Seminar',
      credits: 3,
      type: 'seminar',
      category: 'Core CS',
      year: 3,
      semester: 'A',
      prerequisites: ['c-algo'],
    },
    {
      id: 'c-project',
      code: 'CS399',
      name: 'Capstone Project',
      credits: 6,
      type: 'project',
      category: 'Core CS',
      year: 3,
      semester: 'B',
      prerequisites: ['c-algo', 'c-os'],
    },
  ],
  bundles: [],
};

export function emptyProgram(): Program {
  return {
    name: 'New Degree Program',
    degree: 'B.Sc.',
    institution: '',
    years: 3,
    requiredCredits: 120,
    showSummer: false,
    courses: [],
    bundles: [],
  };
}
